/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package guia2ejercicio4;

import java.util.TreeSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hogar
 */
public class ViewListadoPrecio extends javax.swing.JInternalFrame {

    private TreeSet<Producto> lista;
    private double precioInicial;
    private double precioFinal;

    private DefaultTableModel modelo = new DefaultTableModel() { // utilizamo este objeto para modificar la tabla.

        public boolean isCellEditable(int f, int c) { // este método no permite que las celda sean editable

            return false;
        }
    };

    public ViewListadoPrecio(TreeSet<Producto> lista) {
        initComponents();
        this.lista = lista;
        armarCabecera();
        jtInicial.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtInicial = new javax.swing.JTextField();
        jtFinal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();

        setClosable(true);
        setTitle("Listado por Precio");

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel1.setText("Listad por Precio");

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setText("Entre $");

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel3.setText("y");

        jtInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtInicialActionPerformed(evt);
            }
        });

        jtFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtFinalActionPerformed(evt);
            }
        });

        jTableProductos.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addComponent(jtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtInicialActionPerformed
        // Método del textfried "precio inicial"

        jtFinal.requestFocus();
        
        if (jtInicial.getText() != "" && jtFinal.getText() != "") {

            precioInicial = Double.parseDouble(jtInicial.getText().trim());
            precioFinal = Double.parseDouble(jtFinal.getText().trim());
            borrarFilas();
            for (Producto item : lista) {
                if (item.getPrecio() >= precioInicial && item.getPrecio() <= precioFinal) {
                    modelo.addRow(new Object[]{
                        item.getCodigo(),
                        item.getDescripcion(),
                        item.getPrecio(),
                        item.getStock()
                    });
                }
            }
        }


    }//GEN-LAST:event_jtInicialActionPerformed

    private void jtFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtFinalActionPerformed
        // Método que maneja el evento de la segunda caja
        
        if (jtInicial.getText() != "" && jtFinal.getText() != "") {

            precioInicial = Double.parseDouble(jtInicial.getText().trim());
            precioFinal = Double.parseDouble(jtFinal.getText().trim());
            borrarFilas();
            for (Producto item : lista) {
                if (item.getPrecio() >= precioInicial && item.getPrecio() <= precioFinal) {
                    modelo.addRow(new Object[]{
                        item.getCodigo(),
                        item.getDescripcion(),
                        item.getPrecio(),
                        item.getStock()
                    });
                }
            }
        }
    }//GEN-LAST:event_jtFinalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTextField jtFinal;
    private javax.swing.JTextField jtInicial;
    // End of variables declaration//GEN-END:variables
private void armarCabecera() {

        modelo.addColumn("Código");
        modelo.addColumn("Descripción");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        jTableProductos.setModel(modelo);
    }

    private void borrarFilas() {

        int fila = jTableProductos.getRowCount() - 1;
        for (int i = fila; i >= 0; i--) {

            modelo.removeRow(i);
        }
    }

}
